// Этот файл используется анализом кода для поддержки атрибутов 
// SuppressMessage, примененных в этом проекте. 
// Подавления на уровне проекта либо не имеют целевого объекта, либо для них задан 
// конкретный объект и область пространства имен, тип, член и т. д.
//
// Чтобы добавить подавление к этому файлу, щелкните правой кнопкой 
// мыши сообщение в списке ошибок, укажите на команду "Подавить сообщения" и выберите вариант 
// "В файле проекта для блокируемых предупреждений".
// Нет необходимости вручную добавлять подавления к этому файлу.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "6#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertCurrencyToString(System.Double,ConvertModule.CurrencyType,System.String,System.String,System.Boolean,System.Boolean,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "3#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertDateTimeToString(System.DateTime,System.String,System.Boolean,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "3#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertFloatToString(System.Single,ConvertModule.TextCase,System.Boolean,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "5#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertIntToString(System.Int64,ConvertModule.TextCase,ConvertModule.Sex,System.Boolean,System.Boolean,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "3#", Scope = "member", Target = "ConvertModule.IPlug.#GetCell(ExtendedTypes.ReportTable,System.Int32,System.String,System.Object&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "2#", Scope = "member", Target = "ConvertModule.IPlug.#GetRow(ExtendedTypes.ReportTable,System.Int32,ExtendedTypes.ReportRow&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "3#", Scope = "member", Target = "ConvertModule.IPlug.#ColumnConcat(ExtendedTypes.ReportTable,System.String,System.String,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "2#", Scope = "member", Target = "ConvertModule.IPlug.#RowConcat(ExtendedTypes.ReportRow,System.String,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "3#", Scope = "member", Target = "ConvertModule.IPlug.#TableConcat(ExtendedTypes.ReportTable,System.String,System.String,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "7#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertCurrencyColToString(ExtendedTypes.ReportTable,System.String,ConvertModule.CurrencyType,System.String,System.String,System.Boolean,System.Boolean,ExtendedTypes.ReportTable&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "4#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertDateTimeColToString(ExtendedTypes.ReportTable,System.String,System.String,System.Boolean,ExtendedTypes.ReportTable&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "4#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertFloatColToString(ExtendedTypes.ReportTable,System.String,ConvertModule.TextCase,System.Boolean,ExtendedTypes.ReportTable&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "6#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertIntColToString(ExtendedTypes.ReportTable,System.String,ConvertModule.TextCase,ConvertModule.Sex,System.Boolean,System.Boolean,ExtendedTypes.ReportTable&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "4#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertNameColToCase(ExtendedTypes.ReportTable,System.String,System.String,ConvertModule.TextCase,ExtendedTypes.ReportTable&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "7#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertCurrencyCellToString(ExtendedTypes.ReportRow,System.String,ConvertModule.CurrencyType,System.String,System.String,System.Boolean,System.Boolean,ExtendedTypes.ReportRow&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "4#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertDateTimeCellToString(ExtendedTypes.ReportRow,System.String,System.String,System.Boolean,ExtendedTypes.ReportRow&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "4#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertFloatCellToString(ExtendedTypes.ReportRow,System.String,ConvertModule.TextCase,System.Boolean,ExtendedTypes.ReportRow&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "6#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertIntCellToString(ExtendedTypes.ReportRow,System.String,ConvertModule.TextCase,ConvertModule.Sex,System.Boolean,System.Boolean,ExtendedTypes.ReportRow&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "4#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertNameCellToCase(ExtendedTypes.ReportRow,System.String,System.String,ConvertModule.TextCase,ExtendedTypes.ReportRow&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "3#", Scope = "member", Target = "ConvertModule.IPlug.#ConvertNameToCase(System.String,System.String,ConvertModule.TextCase,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1007:UseGenericsWhereAppropriate", Scope = "member", Target = "ConvertModule.IPlug.#GetCell(ExtendedTypes.ReportTable,System.Int32,System.String,System.Object&)")]
